export type Doctor = {
  _id: string;
  fullName: string;
  gender: "male" | "female" | "other";
  profileImage: string;
  mobileNumber: string;
  specialization: string;
  qualification: string;
  experienceYears: number;
  about: string;
  city: string;
  hospitalName: string;
  consultationFee: number;
  rating: number;
  totalPatients: number;
  totalReviews: number;
  availableDays: string[];
  morningStartTime: string;
  morningEndTime: string;
  eveningStartTime: string;
  eveningEndTime: string;
  slotDurationMinutes: number;
  isAvailable: boolean;
};
